version: "3.1"
services:
  web:
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - /app/node-modules
      - .:/app
  tests:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node-modules
      - .:/app
    command: ["npm","run","test"]
