language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tacobill/docker-react-playground -f Dockerfile.dev .

script:
    - docker run -e CI=true tacobill/docker-react-playground npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-playground"
    env: "DockerReactPlayground-env"
    bucket_name: "elasticbeanstalk-us-east-2-954928359792"
    bucket_path: "docker-react-playground"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"