#Build phase
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS apibuilder
WORKDIR '/usr/share/build'

COPY . .
RUN dotnet build -c Debug


#Run phase
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS api
WORKDIR '/usr/share/api'

COPY --from=apibuilder /usr/share/build/DockerTestWebApi/bin/Debug/netcoreapp3.1/ .
CMD ["dotnet","DockerTestWebApi.dll"]